### PR TITLE
Gracefully handle possibility that status/code is not a number

### PR DESCRIPTION
**Pull request by tpluscode**
A regression I introduced in #15

### CODE REVIEW

**Comment by tpluscode** [comment]
Oh, I notice I forgot about the JSON report.
I will update when you allow 3rd party orbs on CircleCI @AlexZeitler

**Comment by AlexZeitler** [comment]
Should be enabled now

**Comment by tpluscode** [comment]
The nyc setup including the `mocha.opts` files is kinda weird but the best I could muster with mocha. This is how Istanbul actually recommends.

**Comment by AlexZeitler** [comment]
Would using `jest` make things better? I’m about switching anyway.

**Comment by AlexZeitler** [comment]
Are we ok to merge/publish now?

**Comment by tpluscode** [comment]
Yes. In fact I use jest mostly in my projects. I can change that already too

**Comment by AlexZeitler** [comment]
Ok, do you want to create another PR for jest?

**Comment by tpluscode** [comment]
I think I can update this one still

**Comment by AlexZeitler** [comment]
Great 👍🏻

**Comment by AlexZeitler** [comment]
Here we go, 📦  http-problem-details-mapper@0.1.6 is released.

Thanks for the immediate fix and improvements!

**Pull request merged**
