### PR TITLE
Slightly simpler mapper

### PR DESCRIPTION
**Pull request by tpluscode**
* [x] required changes
* [x] tests
* [x] update docs

### CODE REVIEW

**Comment by tpluscode** [comment]
I notice that CI is not triggered on pull requests? Or is it just not reporting back the statuses to GitHub?

**Comment by AlexZeitler** [comment]
I did not exclude any branches in CI config. TBH, i'm not very skilled in dealing with GH and CircleCI because we've been using GitLab internally for a long time now. I will try to find out anyway.

**Comment by AlexZeitler** [comment]
Should be enabled now.

**Comment by AlexZeitler** [comment]
Thanks, 📦  `http-problem-details-mapper@0.1.1` has been released.

**Comment by tpluscode** [comment]
Super. Thanks for releasing all of this promptly

**Pull request merged**
